# Generated by Django 4.0.5 on 2022-09-27 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('nombre_usuario', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=50)),
                ('whatsaap', models.CharField(max_length=20)),
                ('telegram', models.CharField(max_length=30)),
                ('diabetes', models.BooleanField()),
                ('hipertencion', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_juego', models.CharField(max_length=30)),
                ('fecha_juego', models.DateField()),
                ('puntaje_juego', models.IntegerField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipousuario'),
        ),
    ]
